# Generated by Django 4.2.23 on 2025-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(verbose_name='Количество отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
